models:
  - name: t5-base
    max_input_length: 512
  - name: facebook/bart-base
    max_input_length: 1024
  - name: google/pegasus-large
    max_input_length: 1024
  - name: google/bigbird-pegasus-large-arxiv
    max_input_length: 4096
  - name: pszemraj/long-t5-tglobal-base-sci-simplify
    max_input_length: 16384
  - name: allenai/led-base-16384
    max_input_length: 16384
